{
  "formatVersion": "1.1",
  "component": {
    "group": "com.markklim.plugins",
    "module": "popcorn-quality",
    "version": "1.3.2-kotlin23",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.8"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ru.vyarus",
          "module": "gradle-quality-plugin",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.6"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "popcorn-quality-1.3.2-kotlin23.jar",
          "url": "popcorn-quality-1.3.2-kotlin23.jar",
          "size": 63784,
          "sha512": "3f4d81b68a004a58208806c8d64b8e4e81bc7f1cb58b05eadb02e9f0af45c1bf0de05e6240e82e0656c5f3f1a9cebf237578bda8a8106d70739b40cb5e6e2ad3",
          "sha256": "d9529b30a0f4535bbc3d5c4bf0f45d43061b8224c8ebc4b28ebd4fbedd678636",
          "sha1": "66fb283d73ea3cee9704722b9fc60296f275f748",
          "md5": "6819da2e7b3e754662deb1964ff439ce"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 17,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "ru.vyarus",
          "module": "gradle-quality-plugin",
          "version": {
            "requires": "5.0.0"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-gradle-plugin",
          "version": {
            "requires": "1.23.6"
          }
        },
        {
          "group": "io.gitlab.arturbosch.detekt",
          "module": "detekt-api",
          "version": {
            "requires": "1.23.6"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.24"
          }
        }
      ],
      "files": [
        {
          "name": "popcorn-quality-1.3.2-kotlin23.jar",
          "url": "popcorn-quality-1.3.2-kotlin23.jar",
          "size": 63784,
          "sha512": "3f4d81b68a004a58208806c8d64b8e4e81bc7f1cb58b05eadb02e9f0af45c1bf0de05e6240e82e0656c5f3f1a9cebf237578bda8a8106d70739b40cb5e6e2ad3",
          "sha256": "d9529b30a0f4535bbc3d5c4bf0f45d43061b8224c8ebc4b28ebd4fbedd678636",
          "sha1": "66fb283d73ea3cee9704722b9fc60296f275f748",
          "md5": "6819da2e7b3e754662deb1964ff439ce"
        }
      ]
    },
    {
      "name": "javadocElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "popcorn-quality-1.3.2-kotlin23-javadoc.jar",
          "url": "popcorn-quality-1.3.2-kotlin23-javadoc.jar",
          "size": 261,
          "sha512": "e14e2f0d7351131d4a442bb67a62733b08eeff93b658306a949205f01679dd22bf561dcea9150fe09f0343001fcbbf14cc78127cf824c28e87170aa9f861a987",
          "sha256": "4e6624dcaf3637e970e249a98bf66be94bf96452934b4c0bbbd025ceeae0b575",
          "sha1": "f5115730ffadc5795c621d72a3ff3b5426875a63",
          "md5": "f0c8873d2864f43ecae46cdedd27eef8"
        }
      ]
    },
    {
      "name": "sourcesElements",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "popcorn-quality-1.3.2-kotlin23-sources.jar",
          "url": "popcorn-quality-1.3.2-kotlin23-sources.jar",
          "size": 19641,
          "sha512": "b6bdcb6550063773065cd8c6c567e0b2747322b1e803c1d9dfc46cfa6b2b5917671d46c8c5f5691f4e5c5ae11e3267dc0b930e67cfee7349cfe5db6e31d5df9b",
          "sha256": "a369b68f8987ef384def029d8805676bded35a2f732e60c2148598019d49ffab",
          "sha1": "3e00c01b751180b9f45348cd964a941cf725f305",
          "md5": "c29d0e4b6306c6eb3563cdb846f0e59f"
        }
      ]
    }
  ]
}
