{
  "formatVersion": "1.1",
  "component": {
    "group": "org.jetbrains.kotlinx",
    "module": "kotlinx-coroutines-reactive",
    "version": "1.8.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.5"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.8.1.jar",
          "url": "kotlinx-coroutines-reactive-1.8.1.jar",
          "size": 71258,
          "sha512": "2e0bb70183da29668e223b44f7d398032816f9539591591e6137e98ca69c4398540357dcae1c6367f3b51c5bb8baa431d8f485791b4d5da1ce409e56465014b5",
          "sha256": "86ab52d5e86ecdfe93e6b50739d796348397e15e13e0b64e194547d013818b0e",
          "sha1": "2f13c27465c847461364012da6bd8b4eb0de5082",
          "md5": "ebc2a9eb696a5bb02469677823a4e17c"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.8.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-bom",
          "version": {
            "requires": "1.8.1"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "org.reactivestreams",
          "module": "reactive-streams",
          "version": {
            "requires": "1.0.3"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.9.21"
          }
        }
      ],
      "files": [
        {
          "name": "kotlinx-coroutines-reactive-1.8.1.jar",
          "url": "kotlinx-coroutines-reactive-1.8.1.jar",
          "size": 71258,
          "sha512": "2e0bb70183da29668e223b44f7d398032816f9539591591e6137e98ca69c4398540357dcae1c6367f3b51c5bb8baa431d8f485791b4d5da1ce409e56465014b5",
          "sha256": "86ab52d5e86ecdfe93e6b50739d796348397e15e13e0b64e194547d013818b0e",
          "sha1": "2f13c27465c847461364012da6bd8b4eb0de5082",
          "md5": "ebc2a9eb696a5bb02469677823a4e17c"
        }
      ]
    }
  ]
}
